### ISSUE TITLE
输出结果查看

### ISSUE THREAD

**Issue by Tiandishihua** [horizon-research/Fov-3DGS#2]
作者：
   您们好！请问是输出ply格式文件吗？能用原始的高斯查看器打开吗？非常期待您的回复，谢谢！

**Comment by linwk20** [comment]
Yes. We will export each Region/Layer's PLY file separately and combine them into a single point cloud when in use. Additionally, since we have not yet integrated the Fov_Render function with the original Gaussian viewer, it can't be viewed there currently, we can only render Foveated Image given a view now.

```blended_rendering``` [here](https://github.com/horizon-research/Fov-3DGS/blob/4f4777de83832dbe4aab614b237506c7fd2d82a4/fov3dgs/render_compose_gazes_fps.py#L58) is the result of FOV image, we don't save it here because it will affect the FPS test,  you can save it by adding```torchvision.utils.save_image(blended_rendering , os.path.join(render_path, '{0:05d}'.format(idx) + ".png"))```

Let me know if you have further question.
